version: '3.8'

services:
  lionkapp:
    image: ghcr.io/lionk-framework/lionkapp:latest
    ports:
      - "8088:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - lionkapp-network

networks:
  lionkapp-network:
    driver: bridge
    