name: Workflow for app

on: workflow_call

jobs:
  build_test_publish:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: process_pr
      run: python .github/workflows/scripts/app_scripts/process_pr.py
      env: 
        APP_PATH: ${{ vars.APP_PATH }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_BODY: ${{ github.event.pull_request.body }}

    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: build and test app
      run: python .github/workflows/scripts/app_scripts/build_test.py
      env: 
        APP_PATH: ${{ vars.APP_PATH }}

    - name: Set up environment
      run: |
        echo "APP_PATH=${{ vars.APP_PATH }}" >> $GITHUB_ENV
        echo "NEW_VERSION=$(cat newversion.txt)" >> $GITHUB_ENV
        echo "CHANGELOG=$(cat changelog.txt)" >> $GITHUB_ENV
      
    - name: Process csproj
      run: python .github/workflows/scripts/app_scripts/process_csproj.py
      env: 
        APP_PATH: ${{ vars.APP_PATH }}
        NEW_VERSION: ${{ env.NEW_VERSION }}
        CHANGELOG: ${{ env.CHANGELOG }}


    