name: Deploy to Web Server

on:
  pull_request:
    branches:
      - ${{ vars.WEB_LANDING_DEPLOY_BRANCH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WEB_LANDING_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WEB_LANDING_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.WEB_LANDING_HOST }}
          USERNAME: ${{ secrets.WEB_LANDING_USERNAME }}
        run: |
          rsync -avz --delete ./web/html ${{ env.USERNAME }}@${{ env.HOST }}:.
