name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:

  build:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    defaults:
      run:
        working-directory: ${{ vars.SLN_PATH }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    defaults:
      run:
        working-directory: ${{ vars.SLN_PATH }}
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Execute tests 
      run: dotnet test

