name: Preprocessing PR data

on:
  pull_request:
    branches:
      - wof-test
    types: [opened, synchronize, reopened]

jobs:
  check_pr_title:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Process PR title and body
        id: process_title_body
        shell: bash
        run: |
          if [[ "${{env.PR_TITLE}}" == *"app:"* ]]; then
            python .github/workflows/scripts/app_scripts/process_pr.py
          elif [[ "${{env.PR_TITLE}}" == *"nuget:"* ]]; then
            python .github/workflows/scripts/nuget_scripts/process_pr.py
          elif [[ "${{env.PR_TITLE}}" == *"doc:"* ]]; then
            python .github/workflows/scripts/doc_scripts/verify_files.py
          elif [[ "${{env.PR_TITLE}}" == *"wof:"* ]]; then
            python .github/workflows/scripts/wof_scripts/verify_files.py
          else
            echo "Nothing to pre-process"
          fi
                      
        env:
          APP_PATH: ${{ vars.APP_PATH }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}

