name: PR Name validation

on:
  pull_request:
    branches:
      - main

jobs:

  check-pr-name:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR name
      run: |
        title="${{ github.event.pull_request.title }}"
        lower_title=$(echo "$title" | tr '[:upper:]' '[:lower:]')
        if [[ "$lower_title" != *"major"* ]] && [[ "$lower_title" != *"minor"* ]] && [[ "$lower_title" != *"patch"* ]]; then
          echo "Invalid PR title for version increment. Must contain 'major', 'minor', or 'patch'."
          exit 1
        fi
