name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:

  check-pr-name:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR name
      run: |
        if [[ "${{ github.event.pull_request.title }}" != *"major"* ]] && [[ "${{ github.event.pull_request.title }}" != *"minor"* ]] && [[ "${{ github.event.pull_request.title }}" != *"patch"* ]]; then
          echo "Invalid PR title for version increment. Must contain 'major', 'minor', or 'patch'."
          exit 1
        fi

  build:
    needs: check-pr-name
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    defaults:
      run:
        working-directory: ${{ vars.SRC_PATH }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    defaults:
      run:
        working-directory: ${{ vars.SRC_PATH }}
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Execute tests 
      run: dotnet test --no-restore

