name: Preprocessing PR data

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  check_pr_title:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Process PR title and body
        id: process_title_body
        shell: bash
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"app:"* ]]; then
            echo "app"
          elif [[ "${{ github.event.pull_request.title }}" == *"nuget:"* ]]; then
            echo "nuget"
          else
            echo "Nothing to pre-process"
            
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
