name: Check PR Title and Echo Project Versions

on:
  pull_request:
    branches:
      - test

jobs:
  checkout-and-get-pr-title:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pull request title
        id: get_pr_title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Save PR title for next job
        run: echo "PR_TITLE=${{ env.PR_TITLE }}" >> $GITHUB_ENV

  process-pr-title:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION }}
    needs: checkout-and-get-pr-title

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load PR title from previous job
        run: echo "PR_TITLE=${{ needs.checkout-and-get-pr-title.outputs.PR_TITLE }}" >> $GITHUB_ENV

      - name: Process PR title and check projects
        id: process_title
        run: |
          PR_TITLE="${{ env.PR_TITLE }}"
          SRC_PATH="./src_test/"

          echo "Pull Request title: $PR_TITLE"

          # Extract project names and version types from the PR title
          pairs=$(echo "$PR_TITLE" | grep -oE '\b\w+\b (major|minor|patch)')
          if [ -z "$pairs" ]; then
            echo "Pull Request title does not contain version change indication (major, minor, patch)."
            exit 0
          fi

          # Initialize arrays
          declare -a projects
          declare -a types

          # Split projects and types into arrays
          while IFS= read -r pair; do
            project=$(echo "$pair" | awk '{print $1}')
            type=$(echo "$pair" | awk '{print $2}')
            projects+=("$project")
            types+=("$type")
          done <<< "$pairs"

          # Show projects and types
          echo "Projects: ${projects[@]}"
          echo "Types: ${types[@]}"

          # Validate types
          for type in "${types[@]}"; do
            if [[ "$type" != "major" && "$type" != "minor" && "$type" != "patch" ]]; then
              echo "Invalid version type: $type"
              exit 1
            fi
          done

          echo "All version types are valid."

          # Check if project file exists
          for project in "${projects[@]}"; do
            if [ ! -f "$SRC_PATH/$project/$project.csproj" ]; then
              echo "Project file not found: $SRC_PATH/$project/$project.csproj"
              exit 1
            fi
          done

          echo "All project files exist."

          # Save projects and types for next job
          echo "projects=${projects[@]}" >> $GITHUB_ENV
          echo "types=${types[@]}" >> $GITHUB_ENV

  update-project-versions:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION }}
    needs: process-pr-title

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load projects and types from previous job
        run: |
          echo "projects=${{ needs.process-pr-title.outputs.projects }}" >> $GITHUB_ENV
          echo "types=${{ needs.process-pr-title.outputs.types }}" >> $GITHUB_ENV

      - name: Update project versions
        run: |
          projects=(${projects})
          types=(${types})
          SRC_PATH="./src_test/"
          declare -a oldversions
          declare -a newversions

          # Loop through each project and type to populate oldversions and newversions arrays
          for i in "${!projects[@]}"; do
            project=${projects[$i]}
            type=${types[$i]}
            csproj="$SRC_PATH/$project/$project.csproj"
            oldversion=$(grep -oPm1 "(?<=<version>)[^<]+" "$csproj")
            oldversions+=("$oldversion")
            
            IFS='.' read -r -a version_parts <<< "$oldversion"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}

            if [[ "$type" == "major" ]]; then
              major=$((major + 1))
              minor=0
              patch=0
            elif [[ "$type" == "minor" ]]; then
              minor=$((minor + 1))
              patch=0
            elif [[ "$type" == "patch" ]]; then
              patch=$((patch + 1))
            fi

            newversion="$major.$minor.$patch"
            newversions+=("$newversion")

            echo "$project old version: $oldversion, new version: $newversion"
          done

          # Loop through each project and type
          for i in "${!projects[@]}"; do
            project=${projects[$i]}
            type=${types[$i]}
            oldversion=${oldversions[$i]}
            newversion=${newversions[$i]}
            echo "$project apply a $type update to version $oldversion and it will be updated to $newversion"
          done
