name: Check PR Title and Echo Project Versions

on:
  pull_request:
    branches:
      - test

jobs:
  check-pr-title:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pull request title
        id: get_pr_title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Check for .csproj modifications and echo versions
        id: check_projects
        run: |
          PR_TITLE="${{ env.PR_TITLE }}"
          SRC_PATH="./src_test/"

          echo "Pull Request title: $PR_TITLE"

          # Extract project names and version types from the PR title
          projects=$(echo "$PR_TITLE" | grep -oE '\b\w+\b (major|minor|patch)')
          if [ -z "$projects" ]; then
            echo "Pull Request title does not contain version change indication (major, minor, patch)."
            exit 0
          fi

          # Loop through each project and type
          echo "$projects" | while read -r project type; do
            for csproj in $(find $SRC_PATH -name "$project.csproj"); do
              PROJECT_NAME=$(basename $csproj .csproj)
              VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" $csproj)
              echo "$PROJECT_NAME has a $type update to version $VERSION"
            done
          done
