name: Check PR Title and Echo Project Versions

on:
  pull_request:
    branches:
      - test

jobs:
  check-pr-title:
    runs-on: ${{ vars.RUNNER_DISTRIBUTION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pull request title
        id: get_pr_title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Process PR title and check projects
        id: process_title
        run: |
          PR_TITLE="${{ env.PR_TITLE }}"
          SRC_PATH="./src_test/"

          echo "Pull Request title: $PR_TITLE"

          # Extract project names and version types from the PR title
          projects_and_types=$(echo "$PR_TITLE" | grep -oE '\b\w+\b (major|minor|patch)')
          if [ -z "$projects_and_types" ]; then
            echo "Pull Request title does not contain version change indication (major, minor, patch)."
            exit 0
          fi

          # Split projects and types into arrays
          IFS=', ' read -r -a pairs <<< "$projects_and_types"
          declare -a projects
          declare -a types

          # create arrays of projects and types
          for pair in "${pairs[@]}"; do
            project=$(echo $pair | awk '{print $1}')
            type=$(echo $pair | awk '{print $2}')
            projects+=("$project")
            types+=("$type")
          done

          #show projects and types
            echo "Projects: ${projects[@]}"
            echo "Types: ${types[@]}"

          # Validate types and projects
          for type in "${types[@]}"; do
            if [[ "$type" != "major" && "$type" != "minor" && "$type" != "patch" ]]; then
              echo "Invalid version type: $type"
              exit 1
            fi
          done
          
          # check if project file exists
          for project in "${projects[@]}"; do
            if [ ! -f "$SRC_PATH/$project/$project.csproj" ]; then
              echo "Project file not found: $SRC_PATH/$project/$project.csproj"
              exit 1
            fi
          done

          # Loop through each project and type
          for i in "${!projects[@]}"; do
            project=${projects[$i]}
            type=${types[$i]}
            csproj="$SRC_PATH/$project/$project.csproj"
            VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" "$csproj")
            echo "$project has a $type update to version $VERSION"
          done
