version: '3.8'

services:
  landing_page_lionk:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/

  ddns_lionk:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./ddclient:/config
    restart: unless-stopped
